/* eslint-disable camelcase */
import type { Metadata } from 'next'
import { Lato, Carter_One } from 'next/font/google'
import './globals.css'

const lato = Lato({
  subsets: ['latin'],
  weight: ['100', '300', '400', '700', '900'],
})

const carterOne = Carter_One({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${carterOne.className} ${lato.className} bg-basic-bg1 w-screen h-screen`}
      >
        {children}
      </body>
    </html>
  )
}
